export const MOCK_PRODUCTS = [
  {
    id: 1,
    typ: "Kaka",
    title: "Hallongrotor",
    href: "/hallongrotor",
    img: "/assets/kaka1.jpeg",
    ingredients: [
      "Vetemjöl",
      "smör",
      "strösocker",
      "vaniljsocker",
      "hallonsylt",
      "bakpulver",
    ],
    price: 29,
    description:
      "Duka upp till kafferep och dessa godbitar är en absolut favorit.Den lilla söta kakan är spröd och fylld med ljuvlig hallonsylt. Du får en fin kakpåse med 10 stycken av dessa godbitar i.",
  },
  {
    id: 2,
    typ: "Bulle",
    title: "Winnebulle",
    href: "/winnebulle",
    img: "/assets/bulle1.png",
    ingredients: [
      "Vetemjöl",
      "smör",
      "ägg",
      "strösocker",
      "vanilj",
      "grädde",
      "mandel",
      "jäst",
      "salt",
    ],
    price: 58,
    description:
      "Vår Winnebulle är ett mästerverk av brödbakning, bakat med omsorg och de finaste ingredienserna. Med sitt karakteristiska utseende och förföriska doft är det en klassisk favorit",
  },
  {
    id: 3,
    typ: "Bulle",
    title: "Croissant",
    href: "/croissant",
    img: "/assets/bulle2.jpeg",
    ingredients: [
      "Vetemjöl",
      "smör",
      "strösocker",
      "mjölk",
      "ägg",
      "salt",
      "jäst",
    ],
    price: 25,
    description:
      "Denna spröda läckerbit med en krispig yta och ett fluffigt, mjukt innehåll vinner de flestas hjärtan. Till frukost, till kaffepausen eller som en mumsbit på språng är vår croissant ett solklart val för många. Bakad på äkta svenskt smör.",
  },
  {
    id: 4,
    typ: "Tårta",
    title: "Drottningtårta",
    href: "/drottningtarta",
    img: "/assets/tårta3.jpeg",
    ingredients: [
      "Socker",
      "ägg",
      "mjöl",
      "grädde",
      "vaniljkräm",
      "blåbär",
      "hallon",
      "bakpulver",
    ],
    price: 184,
    description:
      "Söta blåbär och syrliga hallon möts i en härlig drottningkompott som varvas med vispad grädde, saftig sockerkaka och egengjord vaniljkräm. Tårtan är toppad med ett rikt lager hallon och blåbär samt en dekorativ kant av spritsad grädde.",
  },
  {
    id: 5,
    typ: "Kaka",
    title: "Kademummakaka",
    href: "/kademummakaka",
    img: "/assets/kaka2.jpeg",
    ingredients: [
      "gräddfil",
      "bikarbonat",
      "smör",
      "socker",
      "ägg",
      "vetemjöl",
      "bakpulver",
      "salt",
      " kardemumma",
      "pärlsocker",
    ],
    price: 32,
    description:
      "En saftig kaka med massor med kardemumma som gör att den både doftar och smakar underbart! Passar perfekt till kaffet!",
  },
  {
    id: 6,
    typ: "Tårta",
    title: "Bjönbär o timjan tårta",
    href: "/bjonbarlimetimjan",
    img: "/assets/tårta4.jpeg",
    ingredients: [
      "smör",
      "strösocker",
      " ägg",
      " mjöl",
      "limefrukter",
      "vaniljextrakt",
      "vispgrädde",
      "florsocker",
      " sirap",
    ],
    price: 194,
    description:
      "Så du kanske tycker att dessa smaker låter lite konstiga tillsammans, särskilt om du aldrig har hört talas om timjan i en dessert tidigare, men det blir alltmer populärt att använda örten i alla möjliga söta saker, och det träffar rätt på den botaniska tårttrenden.",
  },
];
